version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: library
    restart: always
    depends_on:
      - db
    env_file:
      - .env.db
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

volumes:
  postgres_data:
